// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
///<summary>klasa odpowiedzialna za przechowywanie Użytkowników tzn ich nazw,roli oraz haseł</summary>
namespace ApplicationRestaurant.Models
{
    public partial class Users
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Role { get; set; }
        public string Password { get; set; }
    }
}